### ISSUE TITLE
No module named 'datasets.COCO.nms.cpu_nms'

### ISSUE THREAD

**Issue by ShuangjunLiu** [Naman-ntc/Pytorch-Human-Pose-Estimation#17]
I followed the instruction and tried to run a test.  
However, something seems to be wrong with coco api.  
I have installed coco api before which was working.  I used it in my other work before. 

> Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import builder
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/builder.py", line 5, in <module>
    import dataloaders as dataloaders
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/dataloaders.py", line 1, in <module>
    import datasets
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/datasets/__init__.py", line 2, in <module>
    from datasets.coco import *
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/datasets/coco.py", line 2, in <module>
    from datasets.COCO.coco import COCODataset
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/datasets/COCO/__init__.py", line 11, in <module>
    from .coco import COCODataset as coco
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/datasets/COCO/coco.py", line 24, in <module>
    from .nms.nms import oks_nms
  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/datasets/COCO/nms/nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'datasets.COCO.nms.cpu_nms'

**Comment by amin-asdzdh** [comment]
I encountered the same problem, have you figured out how issue?
Cheers

**Comment by ShuangjunLiu** [comment]
> I encountered the same problem, have you figured out how issue?
> Cheers

I thought it missed the necessary Makefile for nms.  
I assumed this part was originated from this [repo](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch). 
You can use their nms instead.

**Comment by Naman-ntc** [comment]
Yes I believe @ShuangjunLiu is right. You need to build nms for COCO dataset as per the instructions [here](https://github.com/Microsoft/human-pose-estimation.pytorch#quick-start)
